import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";
import Link from "next/link";
import { createSupabaseForServerComponent } from "@/lib/supabase.server";
import LogoutLink from "@/utility-components/LogoutLink";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createSupabaseForServerComponent();

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-right" />

        <div className="bg-white text-black py-5 px-7 flex justify-between">
          <ul className="flex gap-4">
            <li>
              <Link href="/">Home</Link>
            </li>
            {session?.user && (
              <>
                <li>
                  <Link href="/admin/internal/businesses">Businesses</Link>
                </li>
              </>
            )}
          </ul>
          <ul className="flex gap-4">
            {session?.user ? (
              <>
                <li>
                  <Link href="/admin/internal/dashboard">Dashboard</Link>
                </li>
                <li>
                  <LogoutLink />
                </li>
              </>
            ) : (
              <li>
                <Link href="/admin/public/login">Login</Link>
              </li>
            )}
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
